config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :buttons
  root to: "buttons#app"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :button

  def self.today
    where created_at: Time.now.beginning_of_day..Time.now
  end

  def duration
    created_at - finished_at
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/button.rb
class Button < ApplicationRecord
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:finished_at, :button_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buttons_controller.rb
class ButtonsController < ApplicationController
  before_action :set_button, only: [:show, :edit, :update, :destroy]

  # GET /buttons
  # GET /buttons.json
  def index
    @buttons = Button.all
  end

  def app
    @buttons = Button.all
  end

  # GET /buttons/1
  # GET /buttons/1.json
  def show
  end

  # GET /buttons/new
  def new
    @button = Button.new
  end

  # GET /buttons/1/edit
  def edit
  end

  # POST /buttons
  # POST /buttons.json
  def create
    @button = Button.new(button_params)

    respond_to do |format|
      if @button.save
        format.html { redirect_to @button, notice: 'Button was successfully created.' }
        format.json { render :show, status: :created, location: @button }
      else
        format.html { render :new }
        format.json { render json: @button.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buttons/1
  # PATCH/PUT /buttons/1.json
  def update
    respond_to do |format|
      if @button.update(button_params)
        format.html { redirect_to @button, notice: 'Button was successfully updated.' }
        format.json { render :show, status: :ok, location: @button }
      else
        format.html { render :edit }
        format.json { render json: @button.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buttons/1
  # DELETE /buttons/1.json
  def destroy
    @button.destroy
    respond_to do |format|
      format.html { redirect_to buttons_url, notice: 'Button was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_button
      @button = Button.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def button_params
      params.require(:button).permit(:name)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buttons_helper.rb
module ButtonsHelper
end

app/views/activities/_activity.html.slim
= activity.duration

app/views/activities/_form.html.slim
= form_for @activity do |f|
  - if @activity.errors.any?
    #error_explanation
      h2 = "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      ul
        - @activity.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :finished_at
    = f.datetime_select :finished_at
  .field
    = f.label :button
    = f.collection_select(:button_id, Button.all, :id, :name, {:prompt => true})
  .actions = f.submit

app/views/activities/edit.html.slim
h1 Editing activity

== render 'form'

=> link_to 'Show', @activity
'|
=< link_to 'Back', activities_path

app/views/activities/index.html.slim
h1 Listing activities

table
  thead
    tr
      th Finished at
      th Button
      th
      th
      th

  tbody
    - @activities.each do |activity|
      tr
        td = activity.finished_at
        td = activity.button
        td = link_to 'Show', activity
        td = link_to 'Edit', edit_activity_path(activity)
        td = link_to 'Destroy', activity, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Activity', new_activity_path

app/views/activities/new.html.slim
h1 New activity

== render 'form'

= link_to 'Back', activities_path

app/views/activities/show.html.slim
p#notice = notice

p
  strong Finished at:
  = @activity.finished_at
p
  strong Button:
  = @activity.button

=> link_to 'Edit', edit_activity_path(@activity)
'|
=< link_to 'Back', activities_path

app/views/buttons/_form.html.slim
= form_for @button do |f|
  - if @button.errors.any?
    #error_explanation
      h2 = "#{pluralize(@button.errors.count, "error")} prohibited this button from being saved:"
      ul
        - @button.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/buttons/app.html.slim
- @buttons.each do |button|
  button id=button.id
    = button.name
    = render button.activities

app/views/buttons/edit.html.slim
h1 Editing button

== render 'form'

=> link_to 'Show', @button
'|
=< link_to 'Back', buttons_path

app/views/buttons/index.html.slim
h1 Listing buttons

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @buttons.each do |button|
      tr
        td = button.name
        td = link_to 'Show', button
        td = link_to 'Edit', edit_button_path(button)
        td = link_to 'Destroy', button, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Button', new_button_path

app/views/buttons/new.html.slim
h1 New button

== render 'form'

= link_to 'Back', buttons_path

app/views/buttons/show.html.slim
p#notice = notice

p
  strong Name:
  = @button.name

=> link_to 'Edit', edit_button_path(@button)
'|
=< link_to 'Back', buttons_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = csrf_meta_tags
      = csp_meta_tag
      = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    body
      = yield